exclude: '^docs/conf.py'

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
  - id: trailing-whitespace
    exclude: ^(tests/data|tests/.*/data)
  - id: check-added-large-files
  - id: check-ast
  - id: check-json
  - id: check-merge-conflict
  - id: check-xml
  - id: check-yaml
    args: ['--allow-multiple-documents']
  - id: debug-statements
  - id: end-of-file-fixer
    exclude: ^(tests/data|tests/.*/data)
  - id: requirements-txt-fixer
  - id: mixed-line-ending
    exclude: ^(tests/data|tests/.*/data)
    args: ['--fix=auto']  # replace 'auto' with 'lf' to enforce Linux/Mac line endings or 'crlf' for Windows

# If you want to avoid flake8 errors due to unused vars or imports:
- repo: https://github.com/myint/autoflake.git
  rev: v2.3.1
  hooks:
  - id: autoflake
    args: [
      --in-place,
      --remove-all-unused-imports,
      --remove-unused-variables,
    ]

- repo: https://github.com/pycqa/isort
  rev: 5.11.5
  hooks:
  - id: isort

- repo: https://github.com/psf/black
  rev: 22.3.0
  hooks:
  - id: black
    language_version: python3

## If like to embrace black styles even in the docs:
# - repo: https://github.com/asottile/blacken-docs
#   rev: v1.11.0
#   hooks:
#   - id: blacken-docs
#     additional_dependencies: [black]

- repo: https://github.com/PyCQA/flake8
  rev: 7.1.1
  hooks:
  - id: flake8
    args: [
      '--max-line-length=88',
      '--ignore=E203,E266,W503,F403,F401,E501,F821',
      '--max-complexity=18',
      '--select=B,C,E,F,W,T4,B9'
    ]
    exclude: (docs/conf.py|^qgis_plugin/)


  ## You can add flake8 plugins via `additional_dependencies`:
  #  additional_dependencies: [flake8-bugbear]


# Strip the output of jupyter notebooks
- repo: https://github.com/kynan/nbstripout
  rev: 0.4.0
  hooks:
    - id: nbstripout

# Interrogate for docstring coverage
- repo: https://github.com/econchick/interrogate
  rev: 1.7.0
  hooks:
    - id: interrogate
      name: check docstring coverage of functions
      args: [-I, -i, -M, --quiet, --fail-under=85, --verbose]
