name: pyws
channels:
  - conda-forge
dependencies:
  - python=3.9.5
  - pip:
    - xlrd==2.0.1
    - matplotlib==3.7.2
    - openpyxl==3.1.2
    - pandoc==2.3
    - pip==21.0.1
    - python-dotenv==1.0.0
    - pywaterinfo==0.7.0
    - rfactor==0.1.2
    - rasterio==1.3.8
    - geopandas==0.13.2
    - numpy==1.25.2
    - scikit-learn==1.3.0
