name: Upload Python Package
on:
  release:
    types: [created]
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: release
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write
      # required for writing to gh-pages
      contents: write

    steps:
    - uses: actions/checkout@v4
    - name: Get all git tags
      run: git fetch --prune --unshallow --tags
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[develop,cache]
        pip install setuptools wheel
    - name: Build documentation
      run: |
        sudo apt-get install -y pandoc
        tox -e docs
    - name: Deploy documentation
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/_build/html
    - name: Build packages
      run: |
        tox -e build
    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
